Milestone 1: Data Foundation and Cleaning 

Week 1: Project Initialization and Dataset Setup 
• Define goals, KPIs, and workflow 
• Load CSVs using pandas 
• Explore schema, types, size, and nulls 
• Perform sampling and memory optimizations
 
Week 2: Preprocessing and Feature Engineering 
• Handle nulls in delay and cancellation columns 
• Create derived features: Month, Day of Week, Hour, Route 
• Format datetime columns 
• Save preprocessed data for fast reuse

In [36]:
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
# import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv(r"E:\AIRFLY - INSIGHTS\flights_sample_3m.csv")

In [37]:
print("printing top five rows")
df.head()

printing top five rows

,FL_DATE,AIRLINE,AIRLINE_DOT,AIRLINE_CODE,DOT_CODE,FL_NUMBER,ORIGIN,ORIGIN_CITY,DEST,DEST_CITY,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,...,ARR_TIME,ARR_DELAY,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT
0,2019-01-09,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,1562,FLL,"Fort Lauderdale, FL",EWR,"Newark, NJ",1155,1151.0,-4.0,19.0,...,1447.0,-14.0,0.0,NaN,0.0,186.0,176.0,153.0,1065.0,NaN,NaN,NaN,NaN,NaN
1,2022-11-19,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,1149,MSP,"Minneapolis, MN",SEA,"Seattle, WA",2120,2114.0,-6.0,9.0,...,2310.0,-5.0,0.0,NaN,0.0,235.0,236.0,189.0,1399.0,NaN,NaN,NaN,NaN,NaN
2,2022-07-22,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,459,DEN,"Denver, CO",MSP,"Minneapolis, MN",954,1000.0,6.0,20.0,...,1252.0,0.0,0.0,NaN,0.0,118.0,112.0,87.0,680.0,NaN,NaN,NaN,NaN,NaN
3,2023-03-06,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,2295,MSP,"Minneapolis, MN",SFO,"San Francisco, CA",1609,1608.0,-1.0,27.0,...,1853.0,24.0,0.0,NaN,0.0,260.0,285.0,249.0,1589.0,0.0,0.0,24.0,0.0,0.0
4,2020-02-23,Spirit Air Lines,Spirit Air Lines: NK,NK,20416,407,MCO,"Orlando, FL",DFW,"Dallas/Fort Worth, TX",1840,1838.0,-2.0,15.0,...,2040.0,-1.0,0.0,NaN,0.0,181.0,182.0,153.0,985.0,NaN,NaN,NaN,NaN,NaN

In [38]:
print("printing lost five rows")
df.tail()

printing lost five rows

,FL_DATE,AIRLINE,AIRLINE_DOT,AIRLINE_CODE,DOT_CODE,FL_NUMBER,ORIGIN,ORIGIN_CITY,DEST,DEST_CITY,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,...,ARR_TIME,ARR_DELAY,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT
2999995,2022-11-13,American Airlines Inc.,American Airlines Inc.: AA,AA,19805,1522,JAX,"Jacksonville, FL",CLT,"Charlotte, NC",1742,1740.0,-2.0,10.0,...,1851.0,-16.0,0.0,NaN,0.0,85.0,71.0,55.0,328.0,NaN,NaN,NaN,NaN,NaN
2999996,2022-11-02,American Airlines Inc.,American Airlines Inc.: AA,AA,19805,1535,ORD,"Chicago, IL",AUS,"Austin, TX",1300,1254.0,-6.0,10.0,...,1519.0,-37.0,0.0,NaN,0.0,176.0,145.0,130.0,977.0,NaN,NaN,NaN,NaN,NaN
2999997,2022-09-11,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,2745,HSV,"Huntsville, AL",ATL,"Atlanta, GA",534,615.0,41.0,16.0,...,805.0,36.0,0.0,NaN,0.0,55.0,50.0,28.0,151.0,0.0,36.0,0.0,0.0,0.0
2999998,2019-11-13,Republic Airline,Republic Airline: YX,YX,20452,6134,BOS,"Boston, MA",LGA,"New York, NY",1600,1555.0,-5.0,19.0,...,1712.0,-16.0,0.0,NaN,0.0,88.0,77.0,50.0,184.0,NaN,NaN,NaN,NaN,NaN
2999999,2019-06-15,Southwest Airlines Co.,Southwest Airlines Co.: WN,WN,19393,2823,LGB,"Long Beach, CA",SJC,"San Jose, CA",730,727.0,-3.0,9.0,...,830.0,-10.0,0.0,NaN,0.0,70.0,63.0,52.0,324.0,NaN,NaN,NaN,NaN,NaN

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000000 entries, 0 to 2999999
Data columns (total 32 columns):
 #   Column                   Dtype
---  ------                   -----
 0   FL_DATE                  object
 1   AIRLINE                  object
 2   AIRLINE_DOT              object
 3   AIRLINE_CODE             object
 4   DOT_CODE                 int64
 5   FL_NUMBER                int64
 6   ORIGIN                   object
 7   ORIGIN_CITY              object
 8   DEST                     object
 9   DEST_CITY                object
 10  CRS_DEP_TIME             int64
 11  DEP_TIME                 float64
 12  DEP_DELAY                float64
 13  TAXI_OUT                 float64
 14  WHEELS_OFF               float64
 15  WHEELS_ON                float64
 16  TAXI_IN                  float64
 17  CRS_ARR_TIME             int64
 18  ARR_TIME                 float64
 19  ARR_DELAY                float64
 20  CANCELLED                float64
 21  CANCELLATION_CODE        object
 22  DIVERTED                 float64
 23  CRS_ELAPSED_TIME         float64
 24  ELAPSED_TIME             float64
 25  AIR_TIME                 float64
 26  DISTANCE                 float64
 27  DELAY_DUE_CARRIER        float64
 28  DELAY_DUE_WEATHER        float64
 29  DELAY_DUE_NAS            float64
 30  DELAY_DUE_SECURITY       float64
 31  DELAY_DUE_LATE_AIRCRAFT  float64
dtypes: float64(19), int64(4), object(9)
memory usage: 732.4+ MB

In [40]:
 # check dimension of dataset
df.shape
print("There are "+ str(df.shape[0]) +" rows and "+ str(df.shape[1]) +" columns from the flight dataset.")

There are 3000000 rows and 32 columns from the flight dataset.

In [41]:
df.columns

Index(['FL_DATE', 'AIRLINE', 'AIRLINE_DOT', 'AIRLINE_CODE', 'DOT_CODE',
       'FL_NUMBER', 'ORIGIN', 'ORIGIN_CITY', 'DEST', 'DEST_CITY',
       'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'TAXI_OUT', 'WHEELS_OFF',
       'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY',
       'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED', 'CRS_ELAPSED_TIME',
       'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'DELAY_DUE_CARRIER',
       'DELAY_DUE_WEATHER', 'DELAY_DUE_NAS', 'DELAY_DUE_SECURITY',
       'DELAY_DUE_LATE_AIRCRAFT'],
      dtype='object')

In [42]:
#Calculate the proportion of missing data
def checkMissing(data,perc=0):
    """ 
    Takes in a dataframe and returns
    the percentage of missing value.
    """
    missing = [(i, data[i].isna().mean()*100) for i in data]
    missing = pd.DataFrame(missing, columns=["column_name", "percentage"])
    missing = missing[missing.percentage > perc]
    print(missing.sort_values("percentage", ascending=False).reset_index(drop=True))

print("Proportion of missing data in columns")
checkMissing(df)

Proportion of missing data in columns
                column_name  percentage
0         CANCELLATION_CODE   97.362000
1         DELAY_DUE_WEATHER   82.204567
2             DELAY_DUE_NAS   82.204567
3        DELAY_DUE_SECURITY   82.204567
4   DELAY_DUE_LATE_AIRCRAFT   82.204567
5         DELAY_DUE_CARRIER   82.204567
6                  AIR_TIME    2.873267
7              ELAPSED_TIME    2.873267
8                 ARR_DELAY    2.873267
9                   TAXI_IN    2.664800
10                WHEELS_ON    2.664800
11                 ARR_TIME    2.664733
12                 TAXI_OUT    2.626867
13               WHEELS_OFF    2.626867
14                DEP_DELAY    2.588133
15                 DEP_TIME    2.587167
16         CRS_ELAPSED_TIME    0.000467

In [43]:
# Cleaning the dataset

print("Cleaning data...")


# --- Handle Nulls & Outliers ---
delay_cols = ['DEP_DELAY', 'ARR_DELAY', 'DELAY_DUE_CARRIER', 
              'DELAY_DUE_WEATHER','DELAY_DUE_NAS','DELAY_DUE_SECURITY',
              'DELAY_DUE_LATE_AIRCRAFT']
for col in delay_cols:
    df[col] = df[col].fillna(0)

Cleaning data...

In [44]:
# Drop unnecessary columns
df = df.drop(columns=['AIRLINE_DOT', 'DOT_CODE', 'FL_NUMBER'])

In [45]:
print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
FL_DATE                          0
AIRLINE                          0
AIRLINE_CODE                     0
ORIGIN                           0
ORIGIN_CITY                      0
DEST                             0
DEST_CITY                        0
CRS_DEP_TIME                     0
DEP_TIME                     77615
DEP_DELAY                        0
TAXI_OUT                     78806
WHEELS_OFF                   78806
WHEELS_ON                    79944
TAXI_IN                      79944
CRS_ARR_TIME                     0
ARR_TIME                     79942
ARR_DELAY                        0
CANCELLED                        0
CANCELLATION_CODE          2920860
DIVERTED                         0
CRS_ELAPSED_TIME                14
ELAPSED_TIME                 86198
AIR_TIME                     86198
DISTANCE                         0
DELAY_DUE_CARRIER                0
DELAY_DUE_WEATHER                0
DELAY_DUE_NAS                    0
DELAY_DUE_SECURITY               0
DELAY_DUE_LATE_AIRCRAFT          0
dtype: int64

In [46]:
# ---Convert numeric columns to smaller float types for memory efficiency
numeric_cols = ['DEP_DELAY', 'ARR_DELAY', 'TAXI_OUT', 'TAXI_IN', 
                'CRS_ELAPSED_TIME', 'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE',
                'DELAY_DUE_CARRIER','DELAY_DUE_WEATHER','DELAY_DUE_NAS',
                'DELAY_DUE_SECURITY','DELAY_DUE_LATE_AIRCRAFT']
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], downcast='float')

In [47]:
# --- Convert to Appropriate Types ---
categorical_cols = ['AIRLINE', 'AIRLINE_CODE', 'ORIGIN', 'ORIGIN_CITY',
                    'DEST', 'DEST_CITY', 'CANCELLATION_CODE']
for col in categorical_cols:
    df[col] = df[col].astype('category')

In [48]:
# --- Handle Nulls & Outliers ---
delay_cols = ['DEP_DELAY', 'ARR_DELAY', 'DELAY_DUE_CARRIER', 
              'DELAY_DUE_WEATHER','DELAY_DUE_NAS','DELAY_DUE_SECURITY',
              'DELAY_DUE_LATE_AIRCRAFT']
for col in delay_cols:
    df[col] = df[col].fillna(0)

In [49]:
# Function to return the main delay cause and its minutes for each row
def get_delay_reason_and_time(row):
    if row['DELAY_DUE_CARRIER'] > 0:
        return "CARRIER", int(row['DELAY_DUE_CARRIER'])
    elif row['DELAY_DUE_WEATHER'] > 0:
        return "WEATHER", int(row['DELAY_DUE_WEATHER'])
    elif row['DELAY_DUE_NAS'] > 0:
        return "NAS", int(row['DELAY_DUE_NAS'])
    elif row['DELAY_DUE_SECURITY'] > 0:
        return "SECURITY", int(row['DELAY_DUE_SECURITY'])
    elif row['DELAY_DUE_LATE_AIRCRAFT'] > 0:
        return "LATE_AIRCRAFT", int(row['DELAY_DUE_LATE_AIRCRAFT'])
    else:
        return "NO_DELAY", 0

In [50]:
# Apply the function row-wise and create two new columns: DELAY_CAUSE & DELAY_MINUTES
df[['DELAY_CAUSE', 'DELAY_MINUTES']] = df.apply(get_delay_reason_and_time, axis=1, result_type='expand')

In [51]:
delay_cols = [
    'DELAY_DUE_CARRIER',
    'DELAY_DUE_WEATHER',
    'DELAY_DUE_NAS',
    'DELAY_DUE_SECURITY',
    'DELAY_DUE_LATE_AIRCRAFT'
]

# Drop in place
df.drop(columns=delay_cols, inplace=True)

In [52]:
df.head().columns

Index(['FL_DATE', 'AIRLINE', 'AIRLINE_CODE', 'ORIGIN', 'ORIGIN_CITY', 'DEST',
       'DEST_CITY', 'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'TAXI_OUT',
       'WHEELS_OFF', 'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME',
       'ARR_DELAY', 'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED',
       'CRS_ELAPSED_TIME', 'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE',
       'DELAY_CAUSE', 'DELAY_MINUTES'],
      dtype='object')

In [53]:
# --- Datetime Conversion ---
df['FL_DATE'] = pd.to_datetime(df['FL_DATE'], errors='coerce')

In [54]:
# Convert to datetime, then extract only the time (HH:MM, no seconds)
df['departure_time'] = pd.to_datetime(
    df['DEP_TIME'].fillna(0).astype(int).astype(str).str.zfill(4),
    format='%H%M',
    errors='coerce'
).dt.time

df['arrival_time'] = pd.to_datetime(
    df['ARR_TIME'].fillna(0).astype(int).astype(str).str.zfill(4),
    format='%H%M',
    errors='coerce'
).dt.time

In [55]:
# Creating a month column
df['Month'] = df['FL_DATE'].dt.month

In [56]:
df.head()

,FL_DATE,AIRLINE,AIRLINE_CODE,ORIGIN,ORIGIN_CITY,DEST,DEST_CITY,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_CAUSE,DELAY_MINUTES,departure_time,arrival_time,Month
0,2019-01-09,United Air Lines Inc.,UA,FLL,"Fort Lauderdale, FL",EWR,"Newark, NJ",1155,1151.0,-4.0,19.0,1210.0,1443.0,4.0,1501,1447.0,-14.0,0.0,NaN,0.0,186.0,176.0,153.0,1065.0,NO_DELAY,0,11:51:00,14:47:00,1
1,2022-11-19,Delta Air Lines Inc.,DL,MSP,"Minneapolis, MN",SEA,"Seattle, WA",2120,2114.0,-6.0,9.0,2123.0,2232.0,38.0,2315,2310.0,-5.0,0.0,NaN,0.0,235.0,236.0,189.0,1399.0,NO_DELAY,0,21:14:00,23:10:00,11
2,2022-07-22,United Air Lines Inc.,UA,DEN,"Denver, CO",MSP,"Minneapolis, MN",954,1000.0,6.0,20.0,1020.0,1247.0,5.0,1252,1252.0,0.0,0.0,NaN,0.0,118.0,112.0,87.0,680.0,NO_DELAY,0,10:00:00,12:52:00,7
3,2023-03-06,Delta Air Lines Inc.,DL,MSP,"Minneapolis, MN",SFO,"San Francisco, CA",1609,1608.0,-1.0,27.0,1635.0,1844.0,9.0,1829,1853.0,24.0,0.0,NaN,0.0,260.0,285.0,249.0,1589.0,NAS,24,16:08:00,18:53:00,3
4,2020-02-23,Spirit Air Lines,NK,MCO,"Orlando, FL",DFW,"Dallas/Fort Worth, TX",1840,1838.0,-2.0,15.0,1853.0,2026.0,14.0,2041,2040.0,-1.0,0.0,NaN,0.0,181.0,182.0,153.0,985.0,NO_DELAY,0,18:38:00,20:40:00,2

In [57]:
import calendar
import pandas as pd
# --- Year ---
df['Year'] = df['FL_DATE'].dt.year
# Ensure FL_DATE is datetime
df['FL_DATE'] = pd.to_datetime(df['FL_DATE'], errors='coerce')

# --- Full month names ---
df['Month'] = df['FL_DATE'].dt.month.apply(lambda x: calendar.month_name[x])

# --- Full day of week names ---
df['DayOfWeek'] = df['FL_DATE'].dt.day_name()

# --- Set categorical ordering for Month ---
month_order = list(calendar.month_name)[1:]  # ['January', 'February', ... 'December']
df['Month'] = pd.Categorical(df['Month'], categories=month_order, ordered=True)

# --- Set categorical ordering for DayOfWeek ---
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
df['DayOfWeek'] = pd.Categorical(df['DayOfWeek'], categories=day_order, ordered=True)

# Preview updated dataframe
df[['FL_DATE', 'Month', 'DayOfWeek', 'Year']].head()

     FL_DATE     Month  DayOfWeek  Year
0 2019-01-09   January  Wednesday  2019
1 2022-11-19  November   Saturday  2022
2 2022-07-22      July     Friday  2022
3 2023-03-06     March     Monday  2023
4 2020-02-23  February     Sunday  2020

In [58]:
df

,FL_DATE,AIRLINE,AIRLINE_CODE,ORIGIN,ORIGIN_CITY,DEST,DEST_CITY,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,...,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_CAUSE,DELAY_MINUTES,departure_time,arrival_time,Month,Year,DayOfWeek
0,2019-01-09,United Air Lines Inc.,UA,FLL,"Fort Lauderdale, FL",EWR,"Newark, NJ",1155,1151.0,-4.0,19.0,1210.0,1443.0,4.0,...,0.0,NaN,0.0,186.0,176.0,153.0,1065.0,NO_DELAY,0,11:51:00,14:47:00,January,2019,Wednesday
1,2022-11-19,Delta Air Lines Inc.,DL,MSP,"Minneapolis, MN",SEA,"Seattle, WA",2120,2114.0,-6.0,9.0,2123.0,2232.0,38.0,...,0.0,NaN,0.0,235.0,236.0,189.0,1399.0,NO_DELAY,0,21:14:00,23:10:00,November,2022,Saturday
2,2022-07-22,United Air Lines Inc.,UA,DEN,"Denver, CO",MSP,"Minneapolis, MN",954,1000.0,6.0,20.0,1020.0,1247.0,5.0,...,0.0,NaN,0.0,118.0,112.0,87.0,680.0,NO_DELAY,0,10:00:00,12:52:00,July,2022,Friday
3,2023-03-06,Delta Air Lines Inc.,DL,MSP,"Minneapolis, MN",SFO,"San Francisco, CA",1609,1608.0,-1.0,27.0,1635.0,1844.0,9.0,...,0.0,NaN,0.0,260.0,285.0,249.0,1589.0,NAS,24,16:08:00,18:53:00,March,2023,Monday
4,2020-02-23,Spirit Air Lines,NK,MCO,"Orlando, FL",DFW,"Dallas/Fort Worth, TX",1840,1838.0,-2.0,15.0,1853.0,2026.0,14.0,...,0.0,NaN,0.0,181.0,182.0,153.0,985.0,NO_DELAY,0,18:38:00,20:40:00,February,2020,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999995,2022-11-13,American Airlines Inc.,AA,JAX,"Jacksonville, FL",CLT,"Charlotte, NC",1742,1740.0,-2.0,10.0,1750.0,1845.0,6.0,...,0.0,NaN,0.0,85.0,71.0,55.0,328.0,NO_DELAY,0,17:40:00,18:51:00,November,2022,Sunday
2999996,2022-11-02,American Airlines Inc.,AA,ORD,"Chicago, IL",AUS,"Austin, TX",1300,1254.0,-6.0,10.0,1304.0,1514.0,5.0,...,0.0,NaN,0.0,176.0,145.0,130.0,977.0,NO_DELAY,0,12:54:00,15:19:00,November,2022,Wednesday
2999997,2022-09-11,Delta Air Lines Inc.,DL,HSV,"Huntsville, AL",ATL,"Atlanta, GA",534,615.0,41.0,16.0,631.0,759.0,6.0,...,0.0,NaN,0.0,55.0,50.0,28.0,151.0,WEATHER,36,06:15:00,08:05:00,September,2022,Sunday
2999998,2019-11-13,Republic Airline,YX,BOS,"Boston, MA",LGA,"New York, NY",1600,1555.0,-5.0,19.0,1614.0,1704.0,8.0,...,0.0,NaN,0.0,88.0,77.0,50.0,184.0,NO_DELAY,0,15:55:00,17:12:00,November,2019,Wednesday
2999999,2019-06-15,Southwest Airlines Co.,WN,LGB,"Long Beach, CA",SJC,"San Jose, CA",730,727.0,-3.0,9.0,736.0,828.0,2.0,...,0.0,NaN,0.0,70.0,63.0,52.0,324.0,NO_DELAY,0,07:27:00,08:30:00,June,2019,Saturday

In [59]:
# Calculating the delay percentage 
# Group by cause and sum delay minutes
DELAY_CAUSE = df.groupby('DELAY_CAUSE')['DELAY_MINUTES'].sum().reset_index()

# Convert minutes → hours
DELAY_CAUSE['DELAY_HOURS'] = DELAY_CAUSE['DELAY_MINUTES'] / 60  

# Calculate percentage contribution based on hours
TOTAL_DELAY = DELAY_CAUSE['DELAY_HOURS'].sum()
DELAY_CAUSE['DELAY_PERCENT'] = (DELAY_CAUSE['DELAY_HOURS'] / TOTAL_DELAY) * 100

# Keep only useful columns
DELAY_CAUSE = DELAY_CAUSE[['DELAY_CAUSE', 'DELAY_HOURS', 'DELAY_PERCENT']].round(3)

print(DELAY_CAUSE)

     DELAY_CAUSE  DELAY_HOURS  DELAY_PERCENT
0        CARRIER   220299.333         52.831
1  LATE_AIRCRAFT    77466.317         18.578
2            NAS    84103.050         20.169
3       NO_DELAY        0.000          0.000
4       SECURITY      771.567          0.185
5        WEATHER    34347.600          8.237

In [60]:
df.columns

Index(['FL_DATE', 'AIRLINE', 'AIRLINE_CODE', 'ORIGIN', 'ORIGIN_CITY', 'DEST',
       'DEST_CITY', 'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'TAXI_OUT',
       'WHEELS_OFF', 'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME',
       'ARR_DELAY', 'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED',
       'CRS_ELAPSED_TIME', 'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE',
       'DELAY_CAUSE', 'DELAY_MINUTES', 'departure_time', 'arrival_time',
       'Month', 'Year', 'DayOfWeek'],
      dtype='object')

In [61]:
df.shape

(3000000, 31)

In [62]:
# Adding ROUTE for easy viewing
# Add ROUTE and ROUTE_CITY to the main df
df['ROUTE'] = df['ORIGIN'].astype(str) + " - " + df['DEST'].astype(str)
df['ROUTE_CITY'] = df['ORIGIN_CITY'].astype(str) + " - " + df['DEST_CITY'].astype(str)

# Create separate route dataframe
route = df[['ROUTE', 'ROUTE_CITY']].copy()

print("Updated main df with ROUTE columns:")
print(df[['ORIGIN','DEST','ROUTE','ROUTE_CITY']].head())

Updated main df with ROUTE columns:
  ORIGIN DEST      ROUTE                           ROUTE_CITY
0    FLL  EWR  FLL - EWR     Fort Lauderdale, FL - Newark, NJ
1    MSP  SEA  MSP - SEA        Minneapolis, MN - Seattle, WA
2    DEN  MSP  DEN - MSP         Denver, CO - Minneapolis, MN
3    MSP  SFO  MSP - SFO  Minneapolis, MN - San Francisco, CA
4    MCO  DFW  MCO - DFW  Orlando, FL - Dallas/Fort Worth, TX

In [63]:
df.columns

Index(['FL_DATE', 'AIRLINE', 'AIRLINE_CODE', 'ORIGIN', 'ORIGIN_CITY', 'DEST',
       'DEST_CITY', 'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'TAXI_OUT',
       'WHEELS_OFF', 'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME',
       'ARR_DELAY', 'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED',
       'CRS_ELAPSED_TIME', 'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE',
       'DELAY_CAUSE', 'DELAY_MINUTES', 'departure_time', 'arrival_time',
       'Month', 'Year', 'DayOfWeek', 'ROUTE', 'ROUTE_CITY'],
      dtype='object')

In [64]:
# Checking the missing values after removing null values and optimizing it.
def checkMissing(data,perc=0):
    """ 
    Takes in a dataframe and returns
    the percentage of missing value.
    """
    missing = [(i, data[i].isna().mean()*100) for i in data]
    missing = pd.DataFrame(missing, columns=["column_name", "percentage"])
    missing = missing[missing.percentage > perc]
    print(missing.sort_values("percentage", ascending=False).reset_index(drop=True))

print("Proportion of missing data in columns")
checkMissing(df)

Proportion of missing data in columns
          column_name  percentage
0   CANCELLATION_CODE   97.362000
1        ELAPSED_TIME    2.873267
2            AIR_TIME    2.873267
3           WHEELS_ON    2.664800
4             TAXI_IN    2.664800
5            ARR_TIME    2.664733
6            TAXI_OUT    2.626867
7          WHEELS_OFF    2.626867
8            DEP_TIME    2.587167
9        arrival_time    0.047200
10     departure_time    0.008067
11   CRS_ELAPSED_TIME    0.000467

In [65]:
# removing cancellation code column to reduce the data redundacy
df = df.drop(columns=['CANCELLATION_CODE'], errors='ignore')

In [66]:
route

             ROUTE                           ROUTE_CITY
0        FLL - EWR     Fort Lauderdale, FL - Newark, NJ
1        MSP - SEA        Minneapolis, MN - Seattle, WA
2        DEN - MSP         Denver, CO - Minneapolis, MN
3        MSP - SFO  Minneapolis, MN - San Francisco, CA
4        MCO - DFW  Orlando, FL - Dallas/Fort Worth, TX
...            ...                                  ...
2999995  JAX - CLT     Jacksonville, FL - Charlotte, NC
2999996  ORD - AUS             Chicago, IL - Austin, TX
2999997  HSV - ATL         Huntsville, AL - Atlanta, GA
2999998  BOS - LGA            Boston, MA - New York, NY
2999999  LGB - SJC        Long Beach, CA - San Jose, CA

[3000000 rows x 2 columns]

In [67]:
pd.set_option('display.max_columns', 29)
df

,FL_DATE,AIRLINE,AIRLINE_CODE,ORIGIN,ORIGIN_CITY,DEST,DEST_CITY,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,...,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_CAUSE,DELAY_MINUTES,departure_time,arrival_time,Month,Year,DayOfWeek,ROUTE,ROUTE_CITY
0,2019-01-09,United Air Lines Inc.,UA,FLL,"Fort Lauderdale, FL",EWR,"Newark, NJ",1155,1151.0,-4.0,19.0,1210.0,1443.0,4.0,...,0.0,186.0,176.0,153.0,1065.0,NO_DELAY,0,11:51:00,14:47:00,January,2019,Wednesday,FLL - EWR,"Fort Lauderdale, FL - Newark, NJ"
1,2022-11-19,Delta Air Lines Inc.,DL,MSP,"Minneapolis, MN",SEA,"Seattle, WA",2120,2114.0,-6.0,9.0,2123.0,2232.0,38.0,...,0.0,235.0,236.0,189.0,1399.0,NO_DELAY,0,21:14:00,23:10:00,November,2022,Saturday,MSP - SEA,"Minneapolis, MN - Seattle, WA"
2,2022-07-22,United Air Lines Inc.,UA,DEN,"Denver, CO",MSP,"Minneapolis, MN",954,1000.0,6.0,20.0,1020.0,1247.0,5.0,...,0.0,118.0,112.0,87.0,680.0,NO_DELAY,0,10:00:00,12:52:00,July,2022,Friday,DEN - MSP,"Denver, CO - Minneapolis, MN"
3,2023-03-06,Delta Air Lines Inc.,DL,MSP,"Minneapolis, MN",SFO,"San Francisco, CA",1609,1608.0,-1.0,27.0,1635.0,1844.0,9.0,...,0.0,260.0,285.0,249.0,1589.0,NAS,24,16:08:00,18:53:00,March,2023,Monday,MSP - SFO,"Minneapolis, MN - San Francisco, CA"
4,2020-02-23,Spirit Air Lines,NK,MCO,"Orlando, FL",DFW,"Dallas/Fort Worth, TX",1840,1838.0,-2.0,15.0,1853.0,2026.0,14.0,...,0.0,181.0,182.0,153.0,985.0,NO_DELAY,0,18:38:00,20:40:00,February,2020,Sunday,MCO - DFW,"Orlando, FL - Dallas/Fort Worth, TX"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999995,2022-11-13,American Airlines Inc.,AA,JAX,"Jacksonville, FL",CLT,"Charlotte, NC",1742,1740.0,-2.0,10.0,1750.0,1845.0,6.0,...,0.0,85.0,71.0,55.0,328.0,NO_DELAY,0,17:40:00,18:51:00,November,2022,Sunday,JAX - CLT,"Jacksonville, FL - Charlotte, NC"
2999996,2022-11-02,American Airlines Inc.,AA,ORD,"Chicago, IL",AUS,"Austin, TX",1300,1254.0,-6.0,10.0,1304.0,1514.0,5.0,...,0.0,176.0,145.0,130.0,977.0,NO_DELAY,0,12:54:00,15:19:00,November,2022,Wednesday,ORD - AUS,"Chicago, IL - Austin, TX"
2999997,2022-09-11,Delta Air Lines Inc.,DL,HSV,"Huntsville, AL",ATL,"Atlanta, GA",534,615.0,41.0,16.0,631.0,759.0,6.0,...,0.0,55.0,50.0,28.0,151.0,WEATHER,36,06:15:00,08:05:00,September,2022,Sunday,HSV - ATL,"Huntsville, AL - Atlanta, GA"
2999998,2019-11-13,Republic Airline,YX,BOS,"Boston, MA",LGA,"New York, NY",1600,1555.0,-5.0,19.0,1614.0,1704.0,8.0,...,0.0,88.0,77.0,50.0,184.0,NO_DELAY,0,15:55:00,17:12:00,November,2019,Wednesday,BOS - LGA,"Boston, MA - New York, NY"
2999999,2019-06-15,Southwest Airlines Co.,WN,LGB,"Long Beach, CA",SJC,"San Jose, CA",730,727.0,-3.0,9.0,736.0,828.0,2.0,...,0.0,70.0,63.0,52.0,324.0,NO_DELAY,0,07:27:00,08:30:00,June,2019,Saturday,LGB - SJC,"Long Beach, CA - San Jose, CA"

In [68]:
df.to_parquet("cleaned_dataset.parquet")

In [69]:
redefined_df = pd.read_parquet('cleaned_dataset.parquet',  columns = ['FL_DATE', 'AIRLINE', 'AIRLINE_CODE', 'ORIGIN', 'ORIGIN_CITY', 'DEST',
       'DEST_CITY', 'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'TAXI_OUT',
       'WHEELS_OFF', 'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME',
       'ARR_DELAY', 'CANCELLED', 'DIVERTED', 'CRS_ELAPSED_TIME',
       'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'DELAY_CAUSE', 'DELAY_MINUTES',
       'departure_time', 'arrival_time', 'Month', 'DayOfWeek', 'Year', 'ROUTE',
       'ROUTE_CITY' ])